#!/usr/bin/env python3
"""Deploy the static site as a Cloudflare Worker behind HTTP Basic Auth.

Two transports, auto-selected:
  - **CI / direct:** set ``CLOUDFLARE_API_TOKEN`` → talk to the Cloudflare API
    directly over TLS with ``Authorization: Bearer``. This is what the GitHub
    Actions ``deploy-site`` job uses (token + ``PREVIEW_PASS`` from repo secrets).
  - **local:** no token → all calls route through the local ``doorman`` proxy,
    which injects the CF API token (cred name ``cloudflare``) so it never touches
    this process.

The site is a single Worker that inlines site/index.html + site/styles.css and
gates them with Basic Auth.

To make the site PUBLIC later: re-run with --no-auth (or delete the auth block),
which redeploys the same Worker without the 401 gate.

Usage (local, via doorman):
    PREVIEW_PASS=... python scripts/deploy_site_preview.py \
        --domain preview.example.com [--user plumbline] [--no-auth]
Usage (CI / direct token):
    CLOUDFLARE_API_TOKEN=... PREVIEW_PASS=... python scripts/deploy_site_preview.py \
        --domain plumbline-bench.org

Local mode requires a `cloudflare` cred in ~/.config/doorman/doorman.yaml with
`hosts: [api.cloudflare.com]`, `tls: true`, an "Edit Cloudflare Workers" token.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

import requests

DOORMAN = "http://127.0.0.1:18443"
CRED = "cloudflare"
SCRIPT_NAME = "plumbline-site"
SITE = Path(__file__).resolve().parent.parent / "site"

# Transport: a direct CLOUDFLARE_API_TOKEN (CI) talks to the API over TLS;
# otherwise route through the local doorman proxy, which injects the token.
_TOKEN = os.environ.get("CLOUDFLARE_API_TOKEN")
S = requests.Session()
if _TOKEN:
    API = "https://api.cloudflare.com/client/v4"  # direct TLS, no proxy
    S.headers["Authorization"] = f"Bearer {_TOKEN}"
    TRANSPORT = "direct token"
else:
    API = "http://api.cloudflare.com/client/v4"  # http scheme -> doorman forwards over TLS
    S.proxies = {"http": DOORMAN}
    S.headers["X-Doorman-Cred"] = CRED
    TRANSPORT = "doorman proxy"


def call(method: str, path: str, **kw):
    r = S.request(method, f"{API}{path}", timeout=60, **kw)
    try:
        body = r.json()
    except ValueError:
        print(f"non-JSON response ({r.status_code}): {r.text[:300]}", file=sys.stderr)
        r.raise_for_status()
        raise
    if not body.get("success", False):
        print(f"{method} {path} -> {r.status_code}\n{json.dumps(body.get('errors'), indent=2)}",
              file=sys.stderr)
        sys.exit(1)
    return body["result"]


def build_worker(html: str, css: str, explore: str, with_auth: bool) -> str:
    auth_block = (
        """
    const pass = env.BASIC_AUTH_PASS;
    if (pass) {
      const user = env.BASIC_AUTH_USER || "plumbline";
      const expected = "Basic " + btoa(user + ":" + pass);
      const got = request.headers.get("Authorization") || "";
      if (!tsEq(got, expected)) {
        return new Response("Authentication required.", {
          status: 401,
          headers: { "WWW-Authenticate": 'Basic realm="plumbline (preview)", charset="UTF-8"',
                     "Cache-Control": "no-store" },
        });
      }
    }
"""
        if with_auth
        else ""
    )
    return f"""// Generated by scripts/deploy_site_preview.py — do not edit by hand.
const HTML = {json.dumps(html)};
const CSS = {json.dumps(css)};
const EXPLORE = {json.dumps(explore)};

const htmlResp = (body) => new Response(body, {{ headers: {{ "content-type": "text/html; charset=utf-8" }} }});

export default {{
  async fetch(request, env) {{{auth_block}
    const path = new URL(request.url).pathname;
    if (path === "/" || path === "/index.html") return htmlResp(HTML);
    if (path === "/explore" || path === "/explore.html") return htmlResp(EXPLORE);
    if (path === "/styles.css")
      return new Response(CSS, {{ headers: {{ "content-type": "text/css; charset=utf-8" }} }});
    return new Response("Not found", {{ status: 404 }});
  }},
}};

function tsEq(a, b) {{
  const e = new TextEncoder();
  const x = e.encode(a), y = e.encode(b);
  if (x.length !== y.length) return false;
  let d = 0;
  for (let i = 0; i < x.length; i++) d |= x[i] ^ y[i];
  return d === 0;
}}
"""


def pick_zone(hostname: str) -> dict:
    zones = call("GET", "/zones?per_page=50")
    matches = [z for z in zones if hostname == z["name"] or hostname.endswith("." + z["name"])]
    if not matches:
        print(f"No Cloudflare zone on this account is a parent of {hostname!r}. "
              f"Zones: {[z['name'] for z in zones]}", file=sys.stderr)
        sys.exit(1)
    return max(matches, key=lambda z: len(z["name"]))  # longest suffix


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--domain", required=True, help="custom hostname, e.g. preview.example.com")
    ap.add_argument("--user", default="plumbline")
    ap.add_argument("--no-auth", action="store_true", help="deploy without Basic Auth (public)")
    args = ap.parse_args()

    password = os.environ.get("PREVIEW_PASS", "")
    if not args.no_auth and not password:
        print("Set PREVIEW_PASS (the Basic Auth password) or pass --no-auth.", file=sys.stderr)
        sys.exit(1)

    html = (SITE / "index.html").read_text()
    css = (SITE / "styles.css").read_text()
    explore = (SITE / "explore.html").read_text()
    worker = build_worker(html, css, explore, with_auth=not args.no_auth)

    print(f"• verifying Cloudflare token ({TRANSPORT})…")
    call("GET", "/user/tokens/verify")
    account_id = call("GET", "/accounts?per_page=1")[0]["id"]
    print(f"• account {account_id}")

    metadata = {
        "main_module": "worker.js",
        "compatibility_date": "2024-11-01",
        "bindings": [{"type": "plain_text", "name": "BASIC_AUTH_USER", "text": args.user}],
    }
    if not args.no_auth:
        metadata["bindings"].append(
            {"type": "secret_text", "name": "BASIC_AUTH_PASS", "text": password}
        )

    print(f"• uploading Worker {SCRIPT_NAME!r} ({len(worker)} bytes, auth={not args.no_auth})…")
    call(
        "PUT",
        f"/accounts/{account_id}/workers/scripts/{SCRIPT_NAME}",
        files={
            "metadata": (None, json.dumps(metadata), "application/json"),
            "worker.js": ("worker.js", worker, "application/javascript+module"),
        },
    )

    zone = pick_zone(args.domain)
    print(f"• attaching custom domain {args.domain} (zone {zone['name']})…")
    call(
        "PUT",
        f"/accounts/{account_id}/workers/domains",
        json={
            "environment": "production",
            "hostname": args.domain,
            "service": SCRIPT_NAME,
            "zone_id": zone["id"],
        },
    )

    print("\n✅ deployed.")
    print(f"   https://{args.domain}")
    if not args.no_auth:
        # Don't echo the password in token (CI) mode — it would land in the
        # Actions log. Locally (doorman) it's the operator's own terminal.
        print(f"   user: {args.user}")
        if not _TOKEN:
            print(f"   pass: {password}")


if __name__ == "__main__":
    main()
