#!/usr/bin/env bash
# Stage every cached artifact (datasets + HF model weights) from the
# plumbline S3 cache onto a fresh GPU rental box.
#
# What this does, in order:
#   1. Sanity-check AWS session creds + disk headroom.
#   2. Sync s3://plumbline-bench/datasets/ → ~/data/
#   3. Sync s3://plumbline-bench/hf-cache/ → ~/.cache/huggingface/
#   4. Set the dataset-root env vars + persist them in ~/.bashrc-plumbline
#      (sourceable from the agent's shell init).
#
# Datasets/weights NOT in S3 (e.g. ETH3D 13-scene full split, anything
# you forgot to cache) still need fetching from upstream — the human
# runbook (GPU_RUNBOOK.md) and the agent runbook
# (docs/AGENT_GPU_RUNBOOK.md) document those per-dataset.

set -euo pipefail

S3_BASE="s3://plumbline-bench"
DATA_ROOT="$HOME/data"
HF_HOME_ROOT="$HOME/.cache/huggingface"

echo "=== plumbline stage_all_data ==="
echo

# Pre-flight: AWS session creds present?
if ! aws sts get-caller-identity >/dev/null 2>&1; then
    cat >&2 <<EOF
ERROR: AWS session creds missing.
On your laptop, run scripts/gpu_box_session_token.sh and paste the
exported variables here. Re-run this script after.
EOF
    exit 2
fi

# Pre-flight: disk
free_gb=$(df -BG --output=avail "$HOME" | tail -1 | tr -d 'G ')
echo "Disk free at \$HOME: ${free_gb} GB"
if [[ "$free_gb" -lt 30 ]]; then
    echo "WARN: ≤30 GB free — datasets + weights total ~35 GB. Consider freeing space first." >&2
fi
echo

# Sync datasets
mkdir -p "$DATA_ROOT"
echo "=== syncing s3://plumbline-bench/datasets/ → $DATA_ROOT/ ==="
aws s3 sync "$S3_BASE/datasets/" "$DATA_ROOT/" \
    --exclude '*/.plumbline_manifest/*' \
    --no-progress 2>&1 | tail -3 || {
    echo "WARN: dataset sync failed; partial cache may still be usable" >&2
}
echo "Dataset tree summary:"
du -sh "$DATA_ROOT"/* 2>/dev/null || true
echo

# Sync HF model weights
mkdir -p "$HF_HOME_ROOT"
echo "=== syncing s3://plumbline-bench/hf-cache/ → $HF_HOME_ROOT/ ==="
aws s3 sync "$S3_BASE/hf-cache/" "$HF_HOME_ROOT/" \
    --no-progress 2>&1 | tail -3 || {
    echo "WARN: hf-cache sync failed; per-model fetches will fall back to HF Hub" >&2
}
echo "HF cache summary:"
du -sh "$HF_HOME_ROOT"/* 2>/dev/null | head -10 || true
echo

# Sync torch.hub cache (Metric3D-v2 uses torch.hub.load_state_dict_from_url,
# which caches to ~/.cache/torch/hub/checkpoints/ and the repo tree to
# ~/.cache/torch/hub/<org>_<repo>_<branch>/ — bypasses HF cache entirely).
TORCH_HUB_ROOT="$HOME/.cache/torch/hub"
mkdir -p "$TORCH_HUB_ROOT"
echo "=== syncing s3://plumbline-bench/torch-hub-cache/hub/ → $TORCH_HUB_ROOT/ ==="
aws s3 sync "$S3_BASE/torch-hub-cache/hub/" "$TORCH_HUB_ROOT/" \
    --no-progress 2>&1 | tail -3 || {
    echo "WARN: torch-hub-cache sync failed; metric3d will re-download on first use" >&2
}
echo "torch.hub cache summary:"
du -sh "$TORCH_HUB_ROOT"/* 2>/dev/null | head -10 || true
echo

# Persist env vars
ENV_FILE="$HOME/.bashrc-plumbline"
cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/stage_all_data.sh
export NYUV2_ROOT=$DATA_ROOT/nyuv2
export KITTI_ROOT=$DATA_ROOT/kitti
export DIODE_ROOT=$DATA_ROOT/diode
export DIODE_MOGE_ROOT=$DATA_ROOT/diode_moge
export ETH3D_ROOT=$DATA_ROOT/eth3d
export DTU_ROOT=$DATA_ROOT/dtu
export GSO_ROOT=$DATA_ROOT/gso
export SEVEN_SCENES_ROOT=$DATA_ROOT/7scenes
export IBIMS1_ROOT=$DATA_ROOT/ibims1
export HF_HOME=$HF_HOME_ROOT
EOF
echo "Wrote env vars to $ENV_FILE"
echo "Source it in your shell:  source $ENV_FILE"
echo
echo "=== stage_all_data done ==="
